/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ups.vista;

import ups.controlador.ControladorCliente;

/**
 *
 * @author dilgg
 */
public class VentanaPrincipal extends javax.swing.JFrame {
private ControladorCliente cC;
   
        
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cC = new ControladorCliente();
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCrear = new javax.swing.JMenuItem();
        menuListarCliente = new javax.swing.JMenuItem();
        menuListarCompra = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuListarLibro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        jMenu1.setText("CLIENTE");

        MenuCrear.setText("Crear");
        MenuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCrear);

        menuListarCliente.setText("Listar Cliente");
        menuListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(menuListarCliente);

        menuListarCompra.setText("Listar Compra");
        menuListarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarCompraActionPerformed(evt);
            }
        });
        jMenu1.add(menuListarCompra);

        menuVenta.setText("Venta");
        menuVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaActionPerformed(evt);
            }
        });
        jMenu1.add(menuVenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("LIBROS");

        menuListarLibro.setText("Lista Libro");
        menuListarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarLibroActionPerformed(evt);
            }
        });
        jMenu2.add(menuListarLibro);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("SALIR");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearActionPerformed
        // TODO add your handling code here:
        CrearCliente crearCliente = new CrearCliente(cC);
        crearCliente.setVisible(true);
        desktopPane.add(crearCliente);
    }//GEN-LAST:event_MenuCrearActionPerformed

    private void menuListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarClienteActionPerformed
        // TODO add your handling code here:
        ListarCliente listarCliente = new ListarCliente(cC);
        listarCliente.setVisible(true);
        desktopPane.add(listarCliente);
    }//GEN-LAST:event_menuListarClienteActionPerformed

    private void menuListarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarCompraActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuListarCompraActionPerformed

    private void menuListarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListarLibroActionPerformed

    private void menuVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaActionPerformed
// TODO add your handling code here:
        
        Venta venta = new Venta(cC);
        venta.setVisible(true);
        desktopPane.add(venta);
        
        
    }//GEN-LAST:event_menuVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCrear;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuListarCliente;
    private javax.swing.JMenuItem menuListarCompra;
    private javax.swing.JMenuItem menuListarLibro;
    private javax.swing.JMenuItem menuVenta;
    // End of variables declaration//GEN-END:variables
}
